<?php  require_once(__DIR__ . "/index.php");
$appid = "YOUR_APPID";
$secretId = "YOUR_SECRETID";
$secretKey = "YOUR_SECRETKEY";
$bucket = "YOUR_BUCKET";
$client = new QcloudImage\CIClient($appid, $secretId, $secretKey, $bucket);
$client->useHttps();
$client->setTimeout(30);
$client->useNewDomain();
var_dump($client->pornDetect(array( "urls" => array( "http://open.youtu.qq.com./static/img/image_porn04.87591fe.jpg" ) )));
var_dump($client->pornDetect(array( "files" => array( "assets/icon_porn04.jpg" ) )));
var_dump($client->tagDetect(array( "url" => "http://open.youtu.qq.com./static/img/imag_02.f43527f.jpg" )));
var_dump($client->tagDetect(array( "file" => "assets/icon_imag_01.jpg" )));
var_dump($client->tagDetect(array( "buffer" => file_get_contents("assets/icon_imag_01.jpg") )));
var_dump($client->idcardDetect(array( "urls" => array( "http://open.youtu.qq.com./static/img/ocr_id_01.883a2df.jpg" ) ), 0));
var_dump($client->idcardDetect(array( "files" => array( "assets/icon_id_01.jpg" ) ), 0));
var_dump($client->idcardDetect(array( "buffers" => array( file_get_contents("assets/icon_id_01.jpg") ) ), 0));
var_dump($client->namecardV2Detect(array( "urls" => array( "http://open.youtu.qq.com/app/img/experience/char_general/ocr_namecard_01.jpg" ) )));
var_dump($client->namecardV2Detect(array( "files" => array( "assets/ocr_namecard_01.jpg" ) )));
var_dump($client->namecardV2Detect(array( "buffers" => array( file_get_contents("assets/ocr_namecard_01.jpg") ) )));
var_dump($client->drivingLicence(array( "file" => "assets/icon_ocr_jsz_01.jpg" ), 1));
var_dump($client->drivingLicence(array( "buffer" => file_get_contents("assets/icon_ocr_jsz_01.jpg") ), 1));
var_dump($client->drivingLicence(array( "url" => "http://open.youtu.qq.com./static/img/ocr_jsz_01.53c2885.jpg" ), 1));
var_dump($client->plate(array( "file" => "assets/icon_ocr_license_3.jpg" )));
var_dump($client->plate(array( "url" => "http://open.youtu.qq.com./static/img/ocr_license_01.d7ac40a.jpg" )));
var_dump($client->bankcard(array( "file" => "assets/ocr_card_01.jpg" )));
var_dump($client->bankcard(array( "buffer" => file_get_contents("assets/ocr_card_01.jpg") )));
var_dump($client->bankcard(array( "url" => "http://open.youtu.qq.com./static/img/ocr_card_01.dd4aada.jpg" )));
var_dump($client->bizlicense(array( "file" => "assets/ocr_yyzz_02.jpg" )));
var_dump($client->bizlicense(array( "buffer" => file_get_contents("assets/ocr_yyzz_02.jpg") )));
var_dump($client->bizlicense(array( "url" => "http://open.youtu.qq.com./static/img/ocr_yyzz_01.1d874f9.jpg" )));
var_dump($client->general(array( "file" => "assets/ocr_common09.jpg" )));
var_dump($client->general(array( "url" => "http://open.youtu.qq.com/static/img/ocr_common05.df60ecc.jpg" )));
var_dump($client->handwriting(array( "file" => "assets/ocr_hw_03.png" )));
var_dump($client->handwriting(array( "url" => "http://open.youtu.qq.com./static/img/ocr_hw_03.2174a0a.jpg" )));
var_dump($client->faceDetect(array( "url" => "https://open.youtu.qq.com/static/img/face_05.b64219d.jpg" ), 0));
var_dump($client->faceDetect(array( "file" => "assets/face_05.jpg" ), 0));
var_dump($client->faceDetect(array( "buffer" => file_get_contents("assets/face_05.jpg") ), 0));
var_dump($client->faceShape(array( "url" => "https://open.youtu.qq.com/static/img/face_05.b64219d.jpg" ), 0));
var_dump($client->faceShape(array( "file" => "assets/face_05.jpg" ), 0));
var_dump($client->faceShape(array( "buffer" => file_get_contents("assets/face_05.jpg") ), 0));
var_dump($client->faceNewPerson("personId0", array( "groupId0" ), array( "url" => "http://open.youtu.qq.com./static/img/face_01.f0c4a0c.jpg" ), "personName0", "personTag0"));
var_dump($client->faceNewPerson("personId1", array( "groupId0" ), array( "file" => "assets/face_02.jpg" ), "personName1", "personTag1"));
var_dump($client->faceNewPerson("personId2", array( "groupId0" ), array( "buffer" => file_get_contents("assets/icon_id_01.jpg") ), "personName2", "personTag2"));
var_dump($client->faceAddFace("person_one", array( "urls" => array( "YOUR URL A", "YOUR URL B" ) )));
var_dump($client->faceAddFace("person_two", array( "files" => array( "F:\\pic\\yang.jpg", "F:\\pic\\yang2.jpg" ) )));
var_dump($client->faceAddFace("person_three", array( "buffers" => array( file_get_contents("F:\\pic\\yang.jpg"), file_get_contents("F:\\pic\\yang2.jpg") ) )));
var_dump($client->faceDelFace("person_one", array( "one" )));
var_dump($client->faceSetInfo("person_one", "fanbing"));
var_dump($client->faceGetInfo("person_one"));
var_dump($client->faceGetGroupIds());
var_dump($client->faceGetPersonIds("group1"));
var_dump($client->faceGetFaceIds("person_one"));
var_dump($client->faceGetFaceInfo("1704147773393235686"));
var_dump($client->faceDelPerson("person_one"));
var_dump($client->faceVerify("person1", array( "url" => "YOUR URL" )));
var_dump($client->faceVerify("person3111", array( "file" => "F:\\pic\\yang3.jpg" )));
var_dump($client->faceVerify("person3111", array( "buffer" => file_get_contents("F:\\pic\\yang3.jpg") )));
var_dump($client->faceIdentify("group1", array( "url" => "YOUR URL" )));
var_dump($client->faceIdentify("group11", array( "file" => "F:\\pic\\yang3.jpg" )));
var_dump($client->faceIdentify("group11", array( "buffer" => file_get_contents("F:\\pic\\yang3.jpg") )));
var_dump($client->faceCompare(array( "url" => "YOUR URL A" ), array( "url" => "YOUR URL B" )));
var_dump($client->faceCompare(array( "file" => "F:\\pic\\yang.jpg" ), array( "file" => "F:\\pic\\yang2.jpg" )));
var_dump($client->faceCompare(array( "buffer" => file_get_contents("F:\\pic\\yang.jpg") ), array( "buffer" => file_get_contents("F:\\pic\\yang3.jpg") )));
var_dump($client->faceIdCardCompare("ID CARD NUM", "NAME", array( "url" => "YOUR URL" )));
var_dump($client->faceIdCardCompare("ID CARD NUM", "NAME", array( "file" => "F:\\pic\\idcard.jpg" )));
var_dump($client->faceIdCardCompare("ID CARD NUM", "NAME", array( "buffer" => file_get_contents("F:\\pic\\idcard.jpg") )));
$obj = $client->faceLiveGetFour();
var_dump($obj);
$faceObj = json_decode($obj, true);
var_dump($faceObj);
$validate_data = "";
if( $faceObj && isset($faceObj["data"]["validate_data"]) ) 
{
	$validate_data = $faceObj["data"]["validate_data"];
}
var_dump($validate_data);
var_dump($client->faceLiveDetectFour($validate_data, array( "file" => "F:\\pic\\ZOE_0171.mp4" ), false, array( "F:\\pic\\idcard.jpg" )));
var_dump($client->faceIdCardLiveDetectFour($validate_data, array( "file" => "F:\\pic\\ZOE_0171.mp4" ), "330782198802084329", "季锦锦"));
var_dump($client->liveDetectPicture(array( "file" => "F:\\pic\\face1.jpg" ), "123456"));
var_dump($client->liveDetectPicture(array( "buffer" => file_get_contents("F:\\pic\\face1.jpg") ), "123456"));
var_dump($client->liveDetectPicture(array( "url" => "YOUR URL" ), "123456"));
var_dump($client->multidentify(array( "file" => "F:\\pic\\r2.jpg" ), array( "group_id" => "tencent" )));
var_dump($client->multidentify(array( "file" => "F:\\pic\\face1.jpg" ), array( "group_ids" => array( "tencent", "qq" ) )));
var_dump($client->multidentify(array( "url" => "YOUR URL" ), array( "group_id" => "tencent" )));
var_dump($client->multidentify(array( "url" => "YOUR URL" ), array( "group_ids" => array( "tencent", "qq" ) )));
?>